### ISSUE TITLE
Name der Zone darf kein Leerzeichen enthalten

### ISSUE THREAD

**Issue by mdettki** [christianTF/LoxBerry-Plugin-squeezelite#14]
Hi,

der Name der Zone darf kein Leerzeichen enthalten. Ich verwende Version 0.1.4.

Viele Grüße
Cali

**Comment by christianTF** [comment]
Ja, das ist ein Fehler, vielen Dank!

**Comment by christianTF** [comment]
Gefixt mit https://github.com/christianTF/LoxBerry-Plugin-squeezelite/commit/9477e0703223ddfecb5948f25b4c1702ad2d6f26 und https://github.com/christianTF/LoxBerry-Plugin-squeezelite/commit/a5434e380dbae551ee72cdc1b08eabdc5f7ed00b
Das kommt dann mit der nächsten Version!
Danke für Probiern!

**Comment by christianTF** [comment]
Die Version 0.1.5 mit der Korrektur ist jetzt im Plugin-Archiv verfügbar.
