### ISSUE TITLE
Integration von UPnPBridge und AirPlay Bridge

### ISSUE THREAD

**Issue by mschlenstedt** [christianTF/LoxBerry-Plugin-squeezelite#17]
Wäre eine feine Sache :-) Ich weiß, ist vielleicht noch etwas früh für neue Feature-Wünsche, aber ich dachte ich bringe es mal an :-)

Die Air Play Bridge läuft bei mir im Moment direkt auf dem LMS, da der aber auf einem NAS läuft sind die Ressourcen doch arg begrenzt.

Infos:
http://forums.slimdevices.com/showthread.php?103728-Announce-UPnPBridge-integrate-UPnP-DLNA-players-with-LMS-(squeeze2upnp)

http://forums.slimdevices.com/showthread.php?105198-ANNOUNCE-AirPlay-Bridge-integrate-AirPlay-devices-with-LMS-(squeeze2raop)

**Comment by christianTF** [comment]
Hi!

Ich hab mit Hismastersvoice Kontakt wegen Synergien seines Musicservers zum Plugin.
Idee ist, dass der LoxBerry mit Plugin auch sein externer Player wird.
Er müsste kein eigenes Image machen, sondern wir integrieren ein Interface für seine Funktionen.
Ich warte mal ab, ob das konkret wird, dann sehen wir weiter :-)

**Comment by christianTF** [comment]
Das mit UPnP und AirPlay find ich sogar ziemlich cool! 
Was ist dein AirPlay-Ziel? Ist das ein Apple TV?

**Comment by mschlenstedt** [comment]
Ich habe hier zwei Radios, die WLAN und Airplay können: 
https://www.amazon.de/gp/product/B0073PXE3A/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1 
Und dann habe ich noch einen RaspPi mit Kodi laufen, den ich ebenfalls 
per Airplay anspreche.

Die beiden Radios laufen absolut stabil, beim Kodi bricht aber der 
Stream ab und zu ab. Ich habe es nur noch nicht geschafft auf der Kiste 
Alsa nachzuinstallieren und direkt einen squeezelite drauf laufen zu 
lassen, daher ist es im Moment eher eine Notlösung.

**Comment by mschlenstedt** [comment]
Obsolete.
