### ISSUE TITLE
-a 160 per Default

### ISSUE THREAD

**Issue by mschlenstedt** [christianTF/LoxBerry-Plugin-squeezelite#18]
Die meisten Webseiten empfehlen einen Buffer von 160 per Default. Sollte auch auf einem Raspi1 keine negativen Effekte haben.

In einer späteren Version konnte man den Buffer editierbar machen und noch ein Feld für zusätzliche individuelle Optionen für squeezelite hinzufügen (so macht es das Kodi Squeezelite Plugin XSqueeze).

**Comment by christianTF** [comment]
Umgesetzt mit https://github.com/christianTF/LoxBerry-Plugin-squeezelite/commit/57dc4f74bc732fb6ae16c0541211cc225c5ff97e
(-a 160)

Mit "Weitere Parameter" kannst du jetzt schon Startoptionen mitgeben.
Mit dem DEV-Branch wird zudem erkannt, ob in den Parametern eine -a Option dabei ist, und mein "festes" -a dann ignoriert.

lg, Christian
