### ISSUE TITLE
Aktuelleres Squeezelite binary verwenden

### ISSUE THREAD

**Issue by christianTF** [christianTF/LoxBerry-Plugin-squeezelite#2]
Aktuellere Version von squeezelite mitliefern oder zur Laufzeit kompilieren

**Comment by mschlenstedt** [comment]
Habe Dir dazu einen Pull Request gesendet.

**Comment by christianTF** [comment]
Ich hab die Änderung in meinen dev-Branch übernommen.
Evt. werde ich noch einbauen, dass die Wahl des Binaries nicht automatisch erfolgt, sondern man in den Einstellungen auswählen kann, ob Binary der Distribution oder das Mitgelieferte. Für den Fall der Fälle (z.B. VM-Image).
