### ISSUE TITLE
0.3 UNSTABLE: Keine Dateiendung bei Virtual Outs

### ISSUE THREAD

**Issue by mschlenstedt** [christianTF/LoxBerry-Plugin-squeezelite#27]
Beim Download der Vorlagedateien für die VirtualOuts wird die Dateiendung .xml nicht angehängt. Getestet mit Chrome.

**Comment by christianTF** [comment]
Fixed in dev 
https://github.com/christianTF/LoxBerry-Plugin-squeezelite/commit/f0025ef766cf50e9e49d56a48e97987abf5c8ed8
