### ISSUE TITLE
Fehlende Klammern im daemon Script?

### ISSUE THREAD

**Issue by mschlenstedt** [christianTF/LoxBerry-Plugin-squeezelite#3]
Kann es sein, dass in Zeile 35 im daemon-Script die eckigen Klammern fehlen?

`if systemctl is-active squeezelite.service`

PS: wie kann man hier eigentlich Code zitieren, ohne dass er immer die ganzen Zeilenumbrüche entfernt? Grrrggghhhh :-(

**Comment by christianTF** [comment]
Danke! Das hat so noch nie funktionieren können ;-) 
Ist gefixt.
https://github.com/christianTF/LoxBerry-Plugin-squeezelite/commit/0275ebb72a38559beadc5e7cda25957f8f2bb2f0
