### ISSUE TITLE
Can't get values from UDP connection

### ISSUE THREAD

**Issue by manuelkirsch** [christianTF/LoxBerry-Plugin-squeezelite#45]
Miniserver is not receiving values from the lms gateway.

3 squeezelite instances.

I have checked all the ip's and ports and I have checked the log files, which are not showing any error or even information beside of the configuration saved messages.

Where can I start to troubleshoot?

Thanks a lot,

Manuel

**Comment by christianTF** [comment]
Hallo Manuel,
for troubleshooting it needs some experience.

First of all, try
ps aux | grep lms2udp 
to find out if the lms2udp.pl process is running.

If NOT, do the following:
- Disable the LMS Gateway in the web interface.
- With putty on shell with loxberry user, run 
/opt/loxberry/webfrontend/cgi/plugins/squeezelite/bin/lms2udp.pl --activate
to run the service in interactive mode. Double-check if you receive values on Loxone.

If IT IS running, do the following:
- In Loxone Config, remove the IP limitation (but not the port) from the Virtual Input and save and restart Miniserver.
- Disable the LMS Gateway in the web interface. The lms2udp.pl service should be stopped (please double-check and,  as appropriate, kill it).
- Use the UDP monitor in Loxone Config to watch for UDP packets.
- Run the service as mentioned above. 
- Immediately after starting the lms2udp.pl, it sends a "Hello Loxone" string via UDP that you should see in UDP monitor.

In the current 0.4.1 release is a bug that calling the plugins index.cgi fails with error 500. Please see https://www.loxforum.com/forum/projektforen/loxberry/plugins/55310-loxberry-plugin-squeezelite?p=96525#post96525 for the solution. I will update the release plugin as soon as possible (presumably on Thursday).

Cheers, Christian

**Comment by christianTF** [comment]
Closed due to inactivity.
