### ISSUE TITLE
Plugin läuft nicht auf non-rasberry Hardware?

### ISSUE THREAD

**Issue by x-sven** [christianTF/LoxBerry-Plugin-squeezelite#49]
Hallo, 
ich verwende loxberry in einer virtuellen Maschine. Die Installation des plugins erkennt das auch brav - "wiringpi" kann entsprechend nicht installiert werden. Beim Aufruf der Seite "http:/IP-LOXBERRY/admin/plugins/squeezelite/index.cgi" erscheint dann allerdings eine Fehlermeldung "Error loading page". 

Der Aufruf des Links in einem neuen Browserfenster ergibt folgende Fehlermeldung: 
Can't locate IO/Interface.pm in @INC (you may need to install the IO::Interface module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at /opt/loxberry/webfrontend/cgi/plugins/squeezelite/index.cgi line 732.
BEGIN failed--compilation aborted at /opt/loxberry/webfrontend/cgi/plugins/squeezelite/index.cgi line 732.

Kann ich noch weitere Infos liefern, oder was testen, dass wir den Fehler eingrenzen können? Wie kann ich das "IO::Interface module" separat installieren???

Grüße
Sven

**Comment by christianTF** [comment]
Hallo Sven,

das ist ein Fehler des verwendeten VM-Images, wo offenbar ein Modul fehlt, das am Original-LoxBerry vorhanden sind.

Du kannst probieren, das damit zu fixen:
`apt-get install libio-interface-perl`

Sollten noch weitere Module fehlen, google einfach nach dem Namen des Moduls (z.B. `IO::Interface perl debian`), damit solltest du die Namen der apt-Pakete herausfinden.

lg, Christian

**Comment by x-sven** [comment]
Das ist es schon gewesen. Danke!
