### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by zmata** [christianTF/LoxBerry-Plugin-squeezelite#52]
I finished Czech translation for curent dev. Could you please add it into next release?
https://github.com/zmata/LoxBerryCz/tree/master/plugins/squeezelite
Thanks Zmata

**Comment by christianTF** [comment]
Hi @zmata,
what is your name (or first name) to mention you in the credits for the translation?
Or do you prefer to be mentioned with your nick?

Christian

**Comment by zmata** [comment]
Hi @christianTF 
My full name is Tomas Zmatlik (Tomáš Zmátlík).
It's not secret nor important ;-) Zmata is OK too. It's my usual nickname and Czech Loxone comunity knows me.
