### ISSUE TITLE
Squeezelite Plugin lässt sich auf LB 1.x VMs nicht installieren

### ISSUE THREAD

**Issue by christianTF** [christianTF/LoxBerry-Plugin-squeezelite#54]
Dadurch, dass mit apt jetzt alle Pakete gemeinsam installiert werden, schlägt die komplette APT-Installation auf, weil wiringpi nicht im Debian-Repo vorhanden ist (nur Raspbian).

Deswegen funktioniert das Plugin nicht mehr auf LB 1.x VMs.

Vermutlich wird es nötig, das Plugin-Interface auf V2 zu heben, um damit plattformabhängig wiringpi zu installieren.

**Comment by mschlenstedt** [comment]
Das war zu 0.2 Zeiten auch schon so. Können wir aber abdrehen. Ist nur eine Zeitersparnis.

**Comment by christianTF** [comment]
Fixed with https://github.com/christianTF/LoxBerry-Plugin-squeezelite/commit/5c779d3a24d18681eadb38bc897099b2c8a78367

@mschlenstedt Das gemeinsame Installieren der APT-Pakete war zwar im LB0.2.3-Code, hat es aber glaube ich nie ins Image geschafft.

Mir gefällt das aktuelle LB1.x-Verhalten eigentlich ganz gut: Wenn ein Paket nicht geht, gehen alle nicht und der Abbruch hinterlässt eine (von den Paketen her) saubere Installation.

Was das Plugin-Interface V2 angeht, müsste man hier wieder dazubauen, dass es ein apt_raspberry, apt_x64, apt_x86 gibt mit unterschiedlichen Paketen.

Ich hab es einfach gefixt, indem ich im daemon in cat /etc/*-release nach raspbian suche, prüfe ob wiringpi schon drauf ist und es sonst (nur unter Raspbian) installiere.
Damit bleibe ich auch LB0.2.x kompatibel.
