### ISSUE TITLE
Gateway funktioniert nicht ohne Miniserver

### ISSUE THREAD

**Issue by mschlenstedt** [christianTF/LoxBerry-Plugin-squeezelite#56]
Ich hatte bei mir aus versehen keinen miniserver konfiguriert. Damit funktioniert das Gateway nicht. Es gibt aber keine Fehlermeldung im WebUI. Nur auf der KOmmandozeile habe ich es herausgefunden:

```
loxberry@loxberrylms:~/webfrontend/htmlauth/plugins/squeezelite $ ./restart_lms2udp.sh
loxberry@loxberrylms:~/webfrontend/htmlauth/plugins/squeezelite $ MSIP  MSPORT 80 LMS 192.168.3.212
Squeezelite Player Plugin LMS2UDP is activated but configuration incomplete. Terminating.

loxberry@loxberrylms:~/webfrontend/htmlauth/plugins/squeezelite $
```

**Comment by christianTF** [comment]
Stimmt!
Core-Developer Leiden, wenn man so oft neue Images installiert, dass man schon die Basis-Config vergisst ;-)
Ich bau mal was ein.

**Comment by christianTF** [comment]
- Unter der NavBar wird angezeigt, ob das Gateway läuft
- Im Log steht dann, dass kein MS konfiguriert ist
- Per (undokumentiertem) Switch in der Config LMS2UDP.sendToMS kann (zu Debuggingzwecken) generell das Senden an den MS abgeschaltet werden.
