### ISSUE TITLE
Temporäre icons in grau

### ISSUE THREAD

**Issue by Woersty** [christianTF/LoxBerry-Plugin-squeezelite#7]
Micha wollte die Icons grau.
Ich habe welche zusammengepfuscht. 
Die kannste nehmen bis deine schönen fertig sind.
[icons.zip](https://github.com/christianTF/LoxBerry-Plugin-squeezelite/files/491300/icons.zip)

**Comment by christianTF** [comment]
Danke! Hab ich übernommen!
https://github.com/christianTF/LoxBerry-Plugin-squeezelite/commit/a23e86032c4d75efbcc498509bc7abe4abe76eb4
